### ISSUE TITLE
Breaking changes does not get detected for response body 

### ISSUE THREAD

**Issue by kimmy1991** [oasdiff/oasdiff#103]
**Describe the bug**
Breaking changes does not get detected when changing a response body property from required to optional

**To Reproduce**

1. Run `oasdiff -fail-on-diff -breaking-only -format text -base base.json -revision revision.json`
2. With [base.txt](https://github.com/Tufin/oasdiff/files/8928499/base.txt) - please convert the txt file and rename it to JSON as I wasn't allowed to upload a json file
3. And [revision.txt](https://github.com/Tufin/oasdiff/files/8928516/revision.txt) - please convert the txt file and rename it to JSON as I wasn't allowed to upload a json file
4. Receive No changes outputted from the cli

**Expected behavior**
As we are changing a property from the response body from required to optional we would expect it to detect a breaking change.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MAC OS BIG SUR version 11.6.2 (20G314) 
 - Browser - N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
We are using latest version v1.1.28 of oasdiff to run the diff against

**Comment by reuvenharrison** [comment]
Hi @kimmy1991,
Thanks for submitting the issue with all the details.
I replicated this behavior and I agree with you that this change should be flagged as a "Breaking-Change".
I am working on a fix.
Reuven

**Comment by reuvenharrison** [comment]
Fixed by https://github.com/Tufin/oasdiff/commit/bbf65cb6f8830a2f0ba6c0c049910234e8d7fdcc
