### ISSUE TITLE
Support ignoring deprecated resource removal

### ISSUE THREAD

**Issue by blva** [oasdiff/oasdiff#116]
**Is your feature request related to a problem? Please describe.**
When we have a deprecated resource for some time, we don't want mark the removal of that resource a breaking change.

**Describe the solution you'd like**
Could we have a flag --ignore-deprecated-removal so that we can optionally remove it without having this reported as a breaking change?

**Describe alternatives you've considered**
Considered using --filter-extension to remove the deprecated word, but seems a bit hacky based on the extension's definition - https://swagger.io/docs/specification/openapi-extensions/. Is that correct?

**Additional context**
We're deciding if we'll be able to use this tool based on the flexibility of contributing with some optional flags to help. Would that be possible? Thanks!

**Comment by reuvenharrison** [comment]
Thanks for reporting this issue.

I suggest to fix this by changing the behavior so that deprecating a resource is **not** breaking.
Only deleting a resource will be breaking.
Any objections?

Please note that I will implement this change for all types of resources that support the deprecated flag:
- Operation
- Parameter
- Header
- Schema

**Comment by blva** [comment]
Thanks for your quick reply!

> depreciating a resource is not a breaking change

We would appreciate to have this implemented. 

> Only deleting a resource will be breaking.

Would it be possible to also ignore the breaking change under a flag? --ignore-deprecated-resource-removal for example. We can also make a contribution for the latter if it's too specific to our business logic and the team is OK with that approach. 

Once again,
Thanks!

**Comment by reuvenharrison** [comment]
I'm committing [a fix](https://github.com/Tufin/oasdiff/pull/118) for the first part: depreciating a resource is not a breaking change.

Regarding the 2nd request to ignore deprecated removals, I understand the motivation but I have a reservation about the proposed solution.
The problem with this solution is that it allows someone to deprecate a resource and very soon afterwards to delete it. In such a case, the new flag will have no effect.
A better removal policy would require a grace period between deprecation and removal which would allow people to know that the resource is about to be removed.
Perhaps we could require publishing an end-of-life date alongside the deprecation and only allow removal after that date. In addition, you would probably also want to control the grace-time, for example 1 week or 30 days.

For example:
When deprecating a resource, the user should specify the end-of-life date with a dedicated extension (e.g., x-eol).
EOL date should be at least `deprecation-grace-period` from now.
The API should not be deleted before this date.

```yaml
paths:
  /api/test:
    get:
      deprecated: true
      x-eol: 13-Jun-2022 
```

Calling oasdiff:
```
oasdiff -deprecation-grace-period=30 -base spec1.yaml -revision spec2.yaml
```

Looking forward to your feedback.

**Comment by reuvenharrison** [comment]
Hi @blva,
I'd like to close this issue.
Do you have any additional feedback?

**Comment by blva** [comment]
Hi! Sorry for the delay I am out of the office. I will circle back to your proposal tomorrow as I will be back from my vacation. Thanks!

**Comment by blva** [comment]
> I'm committing https://github.com/Tufin/oasdiff/pull/118 for the first part: depreciating a resource is not a breaking change.

Thanks for your patience and changes @reuvenharrison! 

> Regarding the 2nd request to ignore deprecated removals, I understand the motivation but I have a reservation about the proposed solution.

Perhaps making the extension name configurable would be helpful to customers? Or more confusing... `x-eol` works. I have no additional feedback regarding this. Thanks!

**Comment by blva** [comment]
Hi @reuvenharrison, I wanted to check in if you have any plans for a timeline as to when `x-eol` could be available so we can plan accordingly. Thanks!

**Comment by reuvenharrison** [comment]
Hi,
This is still on track but may take a couple more weeks.
Thanks for your patience.

**Comment by reuvenharrison** [comment]
Update:
I've started working on this as you can see here: https://github.com/Tufin/oasdiff/tree/deprecation
So far it seems pretty straightforward.
