### ISSUE TITLE
Support ignoring 'Servers Changed'

### ISSUE THREAD

**Issue by bradleyquinn** [oasdiff/oasdiff#123]
It would be nice to be able to ignore the 'Servers changed' property, especially when failing on diff and breaking changes.  We would like to compare a staging environment to a currently deployed version, but doing so always will fail due to the difference in server URLs. 

Thank you!

**Comment by reuvenharrison** [comment]
Could you please provide an example that will enable me to replicate the problem?

**Comment by bradleyquinn** [comment]
Sure, this is what we are running (URLs changed for security purposes). 

docker run --rm -t tufin/oasdiff -fail-on-diff -breaking-only -format html -filter "/api" -base https://qa-mycoolapi.azurewebsites.net/swagger/v1/swagger.json -revision https://dev-mycoolapi.azurewebsites.net/swagger/v1/swagger.json

Would always fail with:
<p>Servers changed</p>
<ul>
<li>Deleted server: <a href="https://qa-mycoolapi.azurewebsites.net">https://qa-mycoolapi.azurewebsites.net</a></li>
</ul>

But in reality that is expected as we are comparing against a deployed version that we know to be stable for backward compatibility issues.  It would be nice to ignore that as a breaking change, something like '-exclude-servers' param would be perfect.

**Comment by reuvenharrison** [comment]
Looks like the spec files are in a private network.
Could you please copy them to a public location?

**Comment by bradleyquinn** [comment]
I am unable to provide real URLs for security purposes, however, I will attempt to make a few swagger.json files that reproduce the issue for you.

**Comment by bradleyquinn** [comment]
[BaseAndRevisionSwaggerDefinitions.zip](https://github.com/Tufin/oasdiff/files/9201329/BaseAndRevisionSwaggerDefinitions.zip)

Sorry for the zip, but GitHub wouldn't let me post json files. 

Thanks again!

**Comment by reuvenharrison** [comment]
Fixed by https://github.com/Tufin/oasdiff/pull/124

**Comment by bradleyquinn** [comment]
Pulled the latest version today and it works perfectly!  Thank you so much :)
