### ISSUE TITLE
Add a version command

### ISSUE THREAD

**Issue by gssbzn** [oasdiff/oasdiff#127]
**Is your feature request related to a problem? Please describe.**
As I was filling the report for #126 there's an ask for version but no easy way to find the version of the bin I have installed, I have to go and do `brew info oasdiff`

**Describe the solution you'd like**
Add a `oasdiff version` or `oasdif -version` option to the CLI, given the use of go native flag implementation more inclined to the use of `oasdiff version` to stay consistent with other go tooling

**Describe alternatives you've considered**
`brew info oasdiff` only works when installed via brew and is not a comamnd many will be familiar vs the common `version` option of many CLIs

**Additional context**
Happy to help to implement this feature as I've done it before for other go CLIs as long as we agree on the option

**Comment by reuvenharrison** [comment]
Hi Gustavo,
I think this is a good idea.
Please feel free to submit a PR.
Thanks,
Reuven
