### ISSUE TITLE
Redirect all error related messages to stderr

### ISSUE THREAD

**Issue by blva** [oasdiff/oasdiff#129]
**Is your feature request related to a problem? Please describe.**
Currently, `oasdiff` only displays exit codes into stderr, which makes it difficult for automation scripts to gather all the displayed information about an error. Furthermore, from a CLI perspective, error messages are expected to be redirected to stderr.

- [Source](https://clig.dev/#the-basics)

**Describe the solution you'd like**
The details in the error ([example](https://github.com/Tufin/oasdiff/blob/ad38c8334453562eecebbb11ffd6945bb41bf046/main.go#L80)) should also be redirected to stderr:

```
failed to load base spec from "openapi_prod.yaml" with openapi_prod.yaml: no such file or directory
Command failed: process encountered problem: exit code 102
```

**Describe alternatives you've considered**
Redirect stdout to a file and check if the command threw an error, if so, cat the stdout and assume it is the error details.

**Additional context**
If we agree this is a good feature to be implemented, I'm happy to discuss further and come up with a PR to contribute and help improve `oasdiff` error handling.

**Comment by effoeffi** [comment]
I suggest to use a logger like [logrus](https://github.com/sirupsen/logrus)
This way we can add functionally like setting the output and print timestamp as part of the the log

**Comment by blva** [comment]
@effoeffi great suggestion, I can do an experiment PR to see what it would look like.
