### ISSUE TITLE
OASDIFF giving error with API specifications with multiple callbacks

### ISSUE THREAD

**Issue by taranjotkaur21** [oasdiff/oasdiff#168]
**Describe the bug**
Getting the error "diff failed with request body reference is nil" while running the oasdiff between two API spec yaml files. It is giving this error in the scenario where specs files have more than one callback tag defined. Files getting compared are identical, then also getting this error.

**To Reproduce**
1. Run `oasdiff  -base spec_1.yaml -revision spec_2.yaml`
2. attached spec_1 and spec_2 
[Files.zip](https://github.com/Tufin/oasdiff/files/10349730/Files.zip)

3. Snippet attached of the error for the comparison of two identical files
![snippet_error](https://user-images.githubusercontent.com/122001377/210712679-a886fd3b-5d94-41dd-b93d-0bd7e0e3e789.jpg)

**Expected behavior**
No output is expected as both files are identical

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10
 - Browser [e.g. chrome, safari] - Local

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by taranjotkaur21** [comment]
Any update on the above issue?

**Comment by reuvenharrison** [comment]
Hi @taranjotkaur21,
Thanks for submitting the issue. I was on vacation for a few days.
I'll take a look today or tomorrow at the latest.
Reuven

**Comment by reuvenharrison** [comment]
It looks like this is caused by a bug the underlying https://github.com/getkin/kin-openapi package.
It can be replicated by loading either one of the specs you provided here and noticing that some of the request bodies within the callbacks are not resolved.
@fenollp could you please take a look and let me know if you need more details to replicate.

**Comment by fenollp** [comment]
Hi @reuvenharrison sorry I missed your hl. 
Was this https://github.com/getkin/kin-openapi/pull/757 the fix you were looking for?
Thanks

**Comment by reuvenharrison** [comment]
Yes @fenollp - this is the fix we needed.
Thanks!
