### ISSUE TITLE
Allow the usage of "-format" with the new method

### ISSUE THREAD

**Issue by peruzzof** [oasdiff/oasdiff#181]
**Is your feature request related to a problem? Please describe.**
I am planning to use oasdiff not to detect changes, but to compare the designed OAPI with the one generated by the code. But I am expecting some differences, so I need to process the result with another mechanism. And will be easier to do so using the JSON or YAML format.

**Describe the solution you'd like**
As JSON is easier to deal in a script I will prefer over YAML, but I can work with the 3 options that used to work with the old method.

**Describe alternatives you've considered**
As the old method is deprecated I hope that this will be implemented before it is removed.

**Additional note**
As not all flags are common between both methods it will be better if this is clear in the documentation and/or help page.

**Comment by reuvenharrison** [comment]
Hi @peruzzof,
The "new method" is only relevant to Breaking-Changes.
The diff formats will remain unchanged and will not be deprecated.
I will try to clarify this in the documentation.
Regards,
Reuven
