### ISSUE TITLE
Coloured output

### ISSUE THREAD

**Issue by EpicWink** [oasdiff/oasdiff#203]
### Problem
A little difficult to distinguish between context, added, deleted, and modified properties in monochromatic output.

### Proposal
Add option to have coloured output:
* For YAML, JSON and text format, if the output is a TTY, using terminal escapes
* For HTML, using CSS (ideally via classes)

Perhaps on by default (`-color auto`), with explicit enable/disable (disregard output not being a TTY for `-color always`).

Blue for context (endpoint method/paths, 'XXX changed'), red for deleted, orange/yellow for modified, and green for added.

### Alternatives
Deal with no colours.

**Comment by JSSAggie** [comment]
![image](https://github.com/Tufin/oasdiff/assets/1988405/80b18dd6-5891-496a-856b-cc8657ec7a9d)

Would this add the ability to turn off the colors?  If so I am all for it.  We are pulling the breaking changes into our API spec pul requests and the color values in the error messages are not helping (:

**Comment by EpicWink** [comment]
CI usually does not have stdout be a TTY, so my proposal would default to no colours in that case

**Comment by reuvenharrison** [comment]
@JSSAggie oasdiff automatically disables colored output when it detects piped output so you can easily remove the colors as follows:
```oasdiff breaking spec1 spec2 | cat```
or
```oasdiff changelog spec1 spec2 | cat```

**Comment by JSSAggie** [comment]
I still think the flag is valuable.  We can pipe out to a json file in the meantime.

**Comment by reuvenharrison** [comment]
Hi @JSSAggie,
https://github.com/Tufin/oasdiff/pull/386 will remove color codes from json and yaml output.
Does this address your requirement?

**Comment by JSSAggie** [comment]
Looks like that will do it.  Thanks

**Comment by ls-jad-elkik** [comment]
It's unclear to me if the `-color always` suggestion was actually implemented in the linked PR.

I would find this helpful since in our CI we'd like to `oasdiff breaking ... | tee artifacts/diff.txt` to be able to process that txt file later on while still showing colors in the CI step itself. So the auto-detection of a TTY with no override is backfiring in our case.

**Comment by reuvenharrison** [comment]
Hi @ls-jad-elkik,
We haven't yet implemented `-color always`.
As of now oasdiff only adds ANSI Color Escape Sequences if the output is **not** piped.
I would recommend running oasdiff twice as a temporary workaround, once with output to the CI step and once again to store the artifact.

In preparation for a proper solution, could you clarify whether you expect artifacts/diff.txt to contain colors or not?

**Comment by ls-jad-elkik** [comment]
Hi @reuvenharrison,

We're going to be using the workaround. The idea was to maybe strip the color codes before storing the artifact, because along with colors the indentation is gone when tty detection kicks in. And indentation is also important to make it readable.

I don't think it's a very critical feature, but it's kind of standard to either have that `--color=[auto|always|off]` flag or `COLOR=XXX` env var or `FORCE_COLOR` env var, etc.

Thanks for the quick reply and clarification.

**Comment by reuvenharrison** [comment]
We will add `--color=[auto|always|never]`
Thanks for your input!

**Comment by reuvenharrison** [comment]
The [latest release](https://github.com/Tufin/oasdiff/releases/tag/v1.10.0) adds support for `color=auto|always|never`
Your feedback is welcome.

**Comment by EpicWink** [comment]
Ahh, I didn't specify which commands I would like to see coloured output in the original request. `diff` I think would also benefit from colours

**Comment by reuvenharrison** [comment]
Hi @EpicWink,
Which format of the diff report are you using? json, text, html, or yaml?
The `json` and `yaml` formats provide a low-level diff report which is not ideal for human-readers.
The diff report in `text` or `html` formats is easier to read.
But the best report for humans is the changelog.

It would be useful to understand this and also the general use-case: how you use the diff output?

By the way, you are welcome to join our slack community where we can discuss this privately:
https://join.slack.com/t/oasdiff/shared_invite/zt-1wvo7wois-ttncNBmyjyRXqBzyg~P6oA

Thanks,
Reuven

**Comment by EpicWink** [comment]
I use the text-format diff, but I hadn't considered using changelog. I think that solves my use-case. I use it as an output in CI

Laurie
________________________________
