### ISSUE TITLE
Path Parameter false positive

### ISSUE THREAD

**Issue by chmoyle-conga** [oasdiff/oasdiff#215]
**Describe the bug**
I keep getting the error `added the new path request parameter 'categoryId' `. Even though its the same path parameter in the base vs the revision. I've tried adding the line to an err-ignore.txt file, but its still giving me the error:

GET /categories/{categoryId}/products added the new path request parameter 'categoryId'

**To Reproduce**
1. Run `oasdiff  -check-breaking -base my.yaml -revision my.json --err-ignore .\Documentation\err-ignore.txt`
2. With base https://pastebin.com/FZLCyCWm
3. And revision https://pastebin.com/SaE42n7H

**Expected behavior**
oasdiff should not be flagging the path parameter as an error because the base and revision are identical

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 (using the windows executable version 1.3.17)

**Comment by reuvenharrison** [comment]
Hi @chmoyle-conga,
Thanks for reporting this issue but unfortunately I haven't been able to replicate it.
I added a [test](https://github.com/Tufin/oasdiff/commit/bef47dbef593e23358b3131b507d30b5e8921580#diff-b7c47b27bdc20f1eab8954afa4cba55f2f13de4f4e57019f955772042c30db92R825) to make sure that the diff of your files is empty, and [all tests, including this one, passed on all platforms including Windows](https://github.com/Tufin/oasdiff/actions/runs/4590546985/jobs/8106161848).

Next steps:
- Please note that my test is using the latest oasdiff version, so perhaps try to replicate again with the latest version v1.3.19
- Make sure that the files you provided on  pastebin.com are identical to the ones you tested locally
- Try to simplify your specs by removing anything that is not related to the problem until you reach the simplest specs that still replicate the issue (note that the files you provided are similar but not identical)

I hope this helps.

**Comment by chmoyle-conga** [comment]
So I was able to narrow the issue down. If I move the path parameter in the yaml file from the path level, to the method level (i.e. move from line 2 to line 32), the error goes away. However, these are generated files so its difficult to do. I would be curious to know why its still showing the error even though I've added the line 
`GET /categories/{categoryId}/products added the new path request parameter 'categoryId'` to my err-ignore.txt file.

**Comment by chmoyle-conga** [comment]
Additionally, I would like to use the github action for this. Is there any way to get that to be the latest version?

**Comment by effoeffi** [comment]
> Additionally, I would like to use the github action for this. Is there any way to get that to be the latest version?

@chmoyle-conga created new version of the _oasdiff-action_ including check-breaking.
You can take a look on the test for how to use it, see [here](https://github.com/Tufin/oasdiff-action/blob/main/.github/workflows/test.yaml#L16)

**Comment by chmoyle-conga** [comment]
Thanks @effoeffi . I think this issue can be closed.
