### ISSUE TITLE
err-ignore subpaths skipped

### ISSUE THREAD

**Issue by chmoyle-conga** [oasdiff/oasdiff#228]
**Describe the bug**
if you have the same breaking change in both a path and its subpath and you try to add both lines to the err-ignore file, the first one will be omitted from the oasdiff, but the subsequent ones will still show up.

**To Reproduce**
1. Run oasdiff on a spec that contains multiple endpoints under the same root and another spec that omits them to produce the following output

error   [api-path-removed-without-deprecation] at original_source=Conga.Revenue.Catalog.API/swagger.json
        in API GET /health
                api path removed without deprecation

error   [api-path-removed-without-deprecation] at original_source=Conga.Revenue.Catalog.API/swagger.json
        in API GET /health/live
                api path removed without deprecation

error   [api-path-removed-without-deprecation] at original_source=Conga.Revenue.Catalog.API/swagger.json
        in API GET /health/ready
                api path removed without deprecation

2. Add all 3 errors to the the err-ignore.txt file:
get /health api path removed without deprecation
get /health/live api path removed without deprecation
get /health/ready api path removed without deprecation

**Expected behavior**
All 3 errors will be omitted from the oasdiff output

**Actual behavior**
only the first /health endpoint is ignored and the /health/ready and /health/live errors still show. Interestingly, even if you only have one of the subpath errors in the err-ignore.txt file, it still just ignores the first /health error. 

I believe its because of the matching logic on line 32 of ignore.go. The logic is if the line contains `(err.Operation+" "+err.Path)` and all 3 of those lines meet that criteria for the /health error.

**Comment by Alexanderchen929** [comment]
+1 also seeing this issue

**Comment by reuvenharrison** [comment]
Hi @chmoyle-conga,
We successfully replicated this issue and, as you said, it is indeed a bug.
Would you be able to share why you are ignoring deprecation-related breaking-changes rather than [following a deprecation policy](https://github.com/Tufin/oasdiff#non-breaking-removal-of-deprecated-resources-beta)?
Thanks,
Reuven

**Comment by chmoyle-conga** [comment]
@reuvenharrison sorry this took so long to answer your question. We're actually using this tool to compare our documentation API spec to our code generated API spec. We have health check endpoints in the code that we don't want in our documentation, so we want to ignore them when oasdiff is run.
