### ISSUE TITLE
Runtime error for an endpoint with no parameters and no return objects while using -strip-prefix-base

### ISSUE THREAD

**Issue by vsarakhan** [oasdiff/oasdiff#243]
**Describe the bug**
Runtime error for an endpoint with no parameters and no return objects while using -strip-prefix-base

**To Reproduce**
1. Run `oasdiff  -check-breaking -base swagger.yaml -revision another_swagger.yaml -strip-prefix-base '/partner-api'`
2. https://codeshare.io/wnoJ97
3. doesn't matter
4. https://codeshare.io/JbXxpd

I'm using the latest 1.5.1 version.

**Comment by reuvenharrison** [comment]
Hi @vsarakhan,
Thanks for reporting this issue.
I have replicated it and working on a fix.
Reuven
