### ISSUE TITLE
Request fields were optional but now required

### ISSUE THREAD

**Issue by vsarakhan** [oasdiff/oasdiff#257]
**Describe the bug**
Request fields were optional but now required

**To Reproduce**
1. Run `oasdiff -check-breaking -base swaggerSpec.yaml -revision openApiSpec.yaml -strip-prefix-base /partner-api -strip-prefix-revision /partner-api`
2. https://codeshare.io/QnD6J7 - swaggerSpec
3. https://codeshare.io/bvbjm6 - openApiSpec
4. Empty output (no diff)

**Expected behavior**

I expect to get a breaking change, because before this the fields were optional, and API users could not fill them out, but now they are required, and people's code can break

**Comment by vsarakhan** [comment]
Additionally: the externalId parameter was nullable, but became not nullable, which can also break the API

**Comment by reuvenharrison** [comment]
Replicated.
Looks like it is related to the schema change being under "Items".
Fix in progress...
