### ISSUE TITLE
Non-breaking changes

### ISSUE THREAD

**Issue by souhailaS** [oasdiff/oasdiff#258]
It would be nice to have an array of non breaking changes same as you do for breaking changes with the json format output.

**Comment by reuvenharrison** [comment]
This is in progress as part of a new changelog feature.
You are welcome to join the discussion: https://github.com/Tufin/oasdiff/discussions/229

**Comment by anikitin** [comment]
@reuvenharrison , I tried "changelog" feature with version 2.1.2. But it seems that it still returns only breaking changes with default parameters. I can see much more changes mentioned in "diff" report than in "changelog" report. Am I missing something?

**Comment by reuvenharrison** [comment]
`oasdiff changelog` returns 3 levels of changes: ERR, WARN and INFO.
The INFO-level changes are the non-breaking ones.
There is on-going work by multiple contributors to reach full coverage so that the changelog will cover all changes.

For example:
```
(base) ➜  oasdiff git:(main) oasdiff changelog data/openapi-test1.yaml data/openapi-test3.yaml
16 changes: 2 error, 4 warning, 10 info
error	[response-success-status-removed] at data/openapi-test3.yaml
	in API GET /api/{domain}/{project}/badges/security-score
		removed the success response with the status '200'

error	[response-success-status-removed] at data/openapi-test3.yaml
	in API GET /api/{domain}/{project}/badges/security-score
		removed the success response with the status '201'

warning	[request-parameter-removed] at data/openapi-test3.yaml
	in API GET /api/{domain}/{project}/badges/security-score
		deleted the 'cookie' request parameter 'test'

warning	[request-parameter-removed] at data/openapi-test3.yaml
	in API GET /api/{domain}/{project}/badges/security-score
		deleted the 'header' request parameter 'user'

warning	[request-parameter-removed] at data/openapi-test3.yaml
	in API GET /api/{domain}/{project}/badges/security-score
		deleted the 'query' request parameter 'filter'

warning	[request-parameter-removed] at data/openapi-test3.yaml
	in API GET /api/{domain}/{project}/install-command
		deleted the 'header' request parameter 'network-policies'

info	[api-global-security-removed]
	in security
		the security scheme 'bearerAuth' was removed from the API

info	[api-schema-removed]
	in components
		removed the schema 'network-policies'

info	[api-schema-removed]
	in components
		removed the schema 'rules'

info	[api-security-component-removed]
	in components
		the component security scheme 'AccessToken' was removed

info	[api-security-component-removed]
	in components
		the component security scheme 'bearerAuth' was removed

info	[api-operation-id-removed] at data/openapi-test1.yaml
	in API GET /api/{domain}/{project}/badges/security-score
		api operation id 'GetSecurityScores' removed and replaced with 'GetSecurityScore'

info	[api-tag-removed] at data/openapi-test1.yaml
	in API GET /api/{domain}/{project}/badges/security-score
		api tag 'security' removed

info	[response-non-success-status-removed] at data/openapi-test3.yaml
	in API GET /api/{domain}/{project}/badges/security-score
		removed the non-success response with the status '400'

info	[api-security-removed] at data/openapi-test3.yaml
	in API POST /register
		the endpoint scheme security 'bearerAuth' was removed from the API

info	[api-security-scope-added] at data/openapi-test3.yaml
	in API POST /register
		the security scope 'write:pets' was added to the endpoint's security scheme 'OAuth'
```

**Comment by anikitin** [comment]
@reuvenharrison , thanks for update, so I am considering this feature as incomplete and looking forward for updates.
If you have any interest, I am building a simple HTML visualizer (based on JS Tabulator library) for changelog in JSON format.
Would be happy to share if you are interested.

![image](https://github.com/Tufin/oasdiff/assets/1359781/b9772453-df80-4dd2-aa66-dde5a6f180f9)

**Comment by reuvenharrison** [comment]
I think your tool may be valuable to oasdiff users :-)
Please share a link and I will also add a reference to it in the readme.

**Comment by reuvenharrison** [comment]
```oasdiff changelog``` currently supports 129 non-breaking checks.
You can see the full list by running ```oasdiff checks --severity info```.
The community is invited to add more checks as needed.
I am closing this as completed.

**Comment by anikitin** [comment]
> I think your tool may be valuable to oasdiff users :-) Please share a link and I will also add a reference to it in the readme.

@reuvenharrison , I owed you this one.

This is a ZIP archive with two files: HTML and JS. You can just open HTML locally in the browser to see how it looks like.
JS file is actually produced from JSON output of oasdiff changelog with some extra fields (I compose it using bash script from real oasdiff output and some variables indicating GitLab revisions).
The UI is based on fantastic Tabulator library (https://tabulator.info/).

Feel free to use in your projects if you find it useful.

[oasdiff-changelog-ui.zip](https://github.com/Tufin/oasdiff/files/13533220/oasdiff-changelog-ui.zip)
