### ISSUE TITLE
Update oasdiff service

### ISSUE THREAD

**Issue by chmoyle-conga** [oasdiff/oasdiff#274]
**Is your feature request related to a problem? Please describe.**
The oasdiff service does not appear to work with the latest version.
It doesn't seem to support all the flags either (i.e. max-circular-dep doesn't seem to work)

**Describe the solution you'd like**
I would like for the cloud solution to be updated to work with the latest oasdiff library and support all the command line arguments.

**Comment by effoeffi** [comment]
@chmoyle-conga oasdiff cloud service updated with a fix.
Can you please share why you prefer using the cloud service over the cli or container?

Regarding support of all arguments, it requires a lot of work, can you please give an example of your top use-cases?
