### ISSUE TITLE
deprecation-days is ignored

### ISSUE THREAD

**Issue by reuvenharrison** [oasdiff/oasdiff#283]
Flag `deprecationDays` is ignored by `check-breaking` which uses hard-coded values instead:
- 31 days for Beta endpoints
- 180 days for Stable endpoints

**How to replicate:**
Note '180 days' in output below, although cmd-line specified deprecation-days=30

cmd-line:
```
oasdiff -base base.yaml -revision revision.yaml -check-breaking --deprecation-days 30
```

Output:
```
error	[api-deprecated-sunset-parse] at data/deprecation/base.yaml
	in API GET /api/test
		api sunset date can't be parsed for deprecated API

error	[api-sunset-date-too-small] at data/deprecation/deprecated-with-sunset.yaml
	in API GET /api/test
		api sunset date 2023-08-02 is too small, must be at least 180 days from now

error	[sunset-deleted] at data/deprecation/deprecated-with-sunset.yaml
	in API GET /api/test
		api sunset date deleted, but deprecated=true kept
```

base.yaml
```
info:
  title: Tufin
  version: 1.0.0
openapi: 3.0.3
paths:
  /api/test:
    post:
      responses:
        201:
          description: OK
    get:
      responses:
        200:
          description: OK
```

revision.yaml
```
info:
  title: Tufin
  version: 1.0.0
openapi: 3.0.3
paths:
  /api/test:
    post:
      responses:
        201:
          description: OK
    get:
      deprecated: true
      x-sunset: "2023-08-02"
      responses:
        200:
          description: OK
```

**Comment by tcdsv** [comment]
please assign me to this issue, thanks.

**Comment by tcdsv** [comment]
I need clarification about the specification of --deprecation-days option:

If deprecation-days is a positive value:
MinSunsetBetaDays and MinSunsetStableDays will be set to the same value as deprecation-days.

If deprecation-days is set to zero:
MinSunsetBetaDays will be 31 and MinSunsetStableDays will be 180, which are their default values.

Is that correct?

**Comment by reuvenharrison** [comment]
I suggest to be able to configure two deprecation-days values, one for stable and another for beta. 

If the user doesn't provide either one of the values, then we should use the default values.

**Comment by tcdsv** [comment]
ok, here's my plan:

1. change the command by adding two different flags for each stability level.
2. the ChangelogFlags struct will be modified to support two distinct stability levels.
3. to pass the values of deprecation-days to GetChecks and GetAllChecks in checker/default_checks.go , I'll use a struct that includes deprecation-days and includeChecks. I think it will provide better flexibility for future updates.
