### ISSUE TITLE
Support oasdiff as an asdf plugin

### ISSUE THREAD

**Issue by JSSAggie** [oasdiff/oasdiff#301]
We would like to use oasdiff as a plugin with [ASDF](https://asdf-vm.com).
https://github.com/asdf-vm/asdf-plugins

We have a mono repo that contains all the API specs for our company.  We interact with that repo to design our APIs.  The local developer experience leverages ASDF for all the development tools that each developer needs in order to work with the API specs.

We are looking at adding breaking change detection to our toolset and would like to use oasdiff.  If you provide an asdf plugin for oasdiff we can plug this into our local and ci/cd process very easily.

**Comment by JSSAggie** [comment]
Looks like this is there now?
https://github.com/oasdiff/asdf-oasdiff

**Comment by reuvenharrison** [comment]
Yes, but it still needs some more work...

**Comment by reuvenharrison** [comment]
Please try it now: https://github.com/oasdiff/asdf-oasdiff
