### ISSUE TITLE
Add --include-checks and other breaking flags to changelog command

### ISSUE THREAD

**Issue by blva** [oasdiff/oasdiff#303]
**Is your feature request related to a problem? Please describe.**
Add `include-checks` flag to changelog
**Describe the solution you'd like**
Add `include-checks` flag to changelog so that changelog generation is consistent with what our developers classify as breaking changes

Ideally, most of existing flags in `breaking` should be present in `changelog` so that it's possible to have consistent `breaking` results within `changelog`

**Comment by reuvenharrison** [comment]
Which "other breaking flags" should we add?

**Comment by blva** [comment]
> Which "other breaking flags" should we add?

Specifically `--err-ignore` and  `--warn-ignore `so that whatever breaking changes were ignored can also be ignored on the changelog. One example use case to do that is when open API specs are being corrected rather than changed.
