### ISSUE TITLE
Can't use oasdif releases with version > 1.5.20 as a go module

### ISSUE THREAD

**Issue by derbylock** [oasdiff/oasdiff#318]
**Describe the bug**
Can't use oasdif releases with version > 1.5.20 as a go module

**To Reproduce**
1. Create new go project. Run `go mod init testoasdiffv2`
2. Run `go get github.com/tufin/oasdiff@v2.1.1`
3. Receive `go: github.com/tufin/oasdiff@v2.1.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/tufin/oasdiff/v2")`
4. Run `go get github.com/tufin/oasdiff/v2@v2.1.1`
5. Receive `go: github.com/tufin/oasdiff@v2.1.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/tufin/oasdiff/v2")`
6. Run `go get github.com/tufin/oasdiff@latest`
7. Run `cat go.mod | grep oasdiff`
8. Receive `github.com/tufin/oasdiff v1.5.20 // indirect`

**Expected behavior**
Steps 3 and 5 should be without errors. It should be possible to use v2 releases as a go module

**Desktop (please complete the following information):**
 - OS: any

**Additional context**

**Comment by reuvenharrison** [comment]
Please see https://github.com/Tufin/oasdiff/discussions/319

**Comment by wtrocki** [comment]
@derbylock In golang when new major version is released it becomes the new module. 
This means that it needs to be imported by:

```
go get github.com/tufin/oasdiff/v2
```

Every time a new major version is released `go get` and `go mod` file will be affected which is standard go procedure. 
`go.mod` file can contain multiple versions as well.

**Comment by wtrocki** [comment]
@reuvenharrison 
I have noticed that the repository doesn't have required go.mod updates

v2 need to be added to the module name and imports will be updated across the repo. 
Then release will become functional as sdk/library.
Happy to create PR if you agree

**Comment by wtrocki** [comment]
@reuvenharrison 
I have noticed that the repository doesn't have to go.mod updates

v2 need to be added to the module name under release and imports will be updated across the repo. 
Then release will become functional as sdk/library

**Comment by reuvenharrison** [comment]
After consideration, we decided to go back to v1 and abandon v2 for now.
I am releasing v1.6.0.

**Comment by derbylock** [comment]
Thanks

**Comment by derbylock** [comment]
> This means that it needs to be imported by:
> go get github.com/tufin/oasdiff/v2

I used exactly the same commanf in step 4
