### ISSUE TITLE
ARM64 (Mac) docker image support

### ISSUE THREAD

**Issue by tibbe** [oasdiff/oasdiff#329]
**Is your feature request related to a problem? Please describe.**
I'd love to run the tool using the supplied docker image for a hassle-free setup on e.g. GitHub Actions.

**Describe the solution you'd like**
The existing Docker Hub image to also be available as arm64.

**Describe alternatives you've considered**
Trying to build and host my own image.

**Comment by reuvenharrison** [comment]
Are you aware of the oasdiff GitHub action?
https://github.com/oasdiff/oasdiff-action
