### ISSUE TITLE
Output breaking changes in a copy/paste format for --err-ignore option 

### ISSUE THREAD

**Issue by timothympace** [oasdiff/oasdiff#333]
**Is your feature request related to a problem? Please describe.**
When breaking changes are detected with this tool, it's not obvious what format should be used in conjunction with `--err-ignore`. The [docs](https://github.com/Tufin/oasdiff/blob/main/BREAKING-CHANGES.md#ignoring-specific-breaking-changes) do describe the format, but it'd be nice to not have to copy and paste parts of the output to form the right structure.

**Describe the solution you'd like**
The output for `oasdiff breaking` should include a copy/pastable version of breaking change errors that can be dropped into a file that's passed to `--err-ignore`.

Example:
```
1 breaking changes: 1 error, 0 warning

error [response-required-property-removed] at revision.json
	in API GET /api/route
		removed the required property 'required' from the response with the '200' status

To ignore: GET /api/route removed the required property 'required' from the response with the '200' status
```

The message output could use some work... but just trying to illustrate the point.

**Describe alternatives you've considered**
Maybe another output format? e.g. via `--format`

**Additional context**
N/A

**Comment by reuvenharrison** [comment]
You can easily do this by piping the output into a file:

```
oasdiff breaking data/openapi-test1.yaml data/openapi-test3.yaml > /tmp/err-ignore.txt
oasdiff breaking data/openapi-test1.yaml data/openapi-test3.yaml --err-ignore /tmp/err-ignore.txt
```

Please let me know if this solution is sufficient.

**Comment by timothympace** [comment]
Oh interesting... how does that work? It looks like the output format is different when redirected to a file somehow?

**Comment by reuvenharrison** [comment]
Yes, the code checks if the output is piped or redirected and, if so, uses a simplified output format.
BTW, you can achieve the same result without a file too:
```
oasdiff breaking data/openapi-test1.yaml data/openapi-test3.yaml | cat
```
