### ISSUE TITLE
Trying to exclude number of paths from breaking command

### ISSUE THREAD

**Issue by AfikGrinstein** [oasdiff/oasdiff#360]
Hi,
I'm new to this tool which I find very astonishing :-).
I want to compare and check for breaking changes but I need to exclude some of my paths.
I tried --match-path and --filter-extension but it doesn't work for me.

Can someone help?

**Comment by reuvenharrison** [comment]
Hi  Afik.
Could you please add instructions to replicate the issue you encountered:
- the two files you compared
- the cmd-line you run
- the expected output

Alternatively, you are welcome to contact me on slack: https://join.slack.com/t/oasdiff/shared_invite/zt-1wvo7wois-ttncNBmyjyRXqBzyg~P6oA

**Comment by AfikGrinstein** [comment]
Thanks for the reply, Reuven.
I manage to make it work using the x-stability-level property.
