### ISSUE TITLE
major version changes

### ISSUE THREAD

**Issue by Angel0926** [oasdiff/oasdiff#388]
Hi,  i use this code: `oasdiff breaking "api/target/generated/openapi.yaml" "myapi-latest.yaml" --fail-on ERR`
 
this is working, but i want to understand that the build of this code fails when our major version changes?

**Comment by reuvenharrison** [comment]
Sorry, but I don't understand the question.
Could you share the specs you compare, the output you receive and the desired output?

**Comment by Angel0926** [comment]
I compare the current and previous version of openapi.yaml and if there are changes, the build failed, but I need it so that if the version changes, the build doesn’t failed

**Comment by reuvenharrison** [comment]
Okay, I think I understand now.
You want to enforce a policy which allows breaking changes only if the major version was changed.

For example:
A breaking change between v1.7.1 -> v1.8.0 is allowed
A breaking change between v1.7.1 -> v1.7.2 is not allowed

Is this correct?

Are there any other constraints you require for breaking changes? For example:
- an end point should be deprecated before it's deleted
- an endpoint can only be deleted after the sunset date
Etc.

**Comment by Angel0926** [comment]
@reuvenharrison no) i want A breaking change between v1.7.1 -> v1.7.2 is allowed, 
that is, if the versions are different, then allow


or if we in build process can say or send cahnges and asked we agree with changes if yes allow if not failed

**Comment by Angel0926** [comment]
@reuvenharrison also i want understand can i choose only that scenaries where i want allow break and changes? 

--include-checks do it, or it adds scripts to the existing list?

**Comment by reuvenharrison** [comment]
Hi @Angel0926,
I think your requirements can be solved but they would require some development, either within oasdiff or as an external program.
I invite you to join our slack community where we can discuss this privately:
https://join.slack.com/t/oasdiff/shared_invite/zt-1wvo7wois-ttncNBmyjyRXqBzyg~P6oA
Regards,
Reuven
