### ISSUE TITLE
Ability to exclude remote references (local files)

### ISSUE THREAD

**Issue by kmcquade** [oasdiff/oasdiff#438]
# Is your feature request related to a problem? Please describe.

Hi, we use oasdiff pretty heavily and it's been super super useful.

I have a situation where there is an OpenAPI spec - specifically, [this one](https://raw.githubusercontent.com/CVEProject/cve-services/dev/api-docs/openapi.json) - which has fields like this:

```json
        "responses": {
          "200": {
            "description": "A list of the newly reserved CVE IDs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../schemas/cve-id/create-cve-ids-response.json"
                }
              }
            }
          },
```

These are references to local files, which are covered in the Swagger Smartbear docs [here](https://swagger.io/docs/specification/using-ref/#:~:text=The%20element%20of%20the%20document%20located%20in%20the%20parent%20folder).

In our situation, will have a single OpenAPI file, but will not have access to those other local files. 

## Steps to reproduce

1. Run these commands:

```bash
curl https://raw.githubusercontent.com/CVEProject/cve-services/dev/api-docs/openapi.json -o base.json
cat <<EOF >revision.yml
openapi: 3.0.0
paths: {}
EOF

oasdiff diff ./base.json ./revision.yml
```

2. Observe that the output indicates a failure to load the reference to another local file:

![image](https://github.com/Tufin/oasdiff/assets/3422255/edaff9a1-9103-4c8c-b994-c66bbda65664)

Text:

```
Error: failed to load base spec from "./base.json" with open ../schemas/user/get-user-response.json: no such file or directory
```

# Describe the solution you'd like

It would be super helpful if we could exclude remote references to avoid failure.

# Describe alternatives you've considered

Currently, I have this ugly parsing and replacement workaround in my python code. It parses the oasdiff output and deletes items that are clearly local refs.

```python
def remove_local_refs(data):
    """Workaround for: https://github.com/Tufin/oasdiff/issues/438"""
    if isinstance(data, dict):
        keys_to_delete = []
        for key, value in data.items():
            if key == "$ref" and isinstance(value, str) and not value.startswith(("http://", "https://", "#")):
                return None  # Return None to indicate this item should be removed
            result = remove_local_refs(value)
            if result is None:
                keys_to_delete.append(key)
            else:
                data[key] = result
        for key in keys_to_delete:
            del data[key]
        return data
    elif isinstance(data, list):
        return [remove_local_refs(item) for item in data if remove_local_refs(item) is not None]
    else:
        return data


def remove_local_refs_from_file(file_path: str):
    with open(file_path, 'r') as base_file:
        base_data = yaml.safe_load(base_file)
    base_data = remove_local_refs(base_data)
    with open(file_path, 'w') as base_file:
        yaml.dump(base_data, base_file)

```

# Additional context

As mentioned, we will have a single OpenAPI file, but will not have access to those other local files. 

Happy to answer any questions that I can. Thank you for making such a great tool!

**Comment by reuvenharrison** [comment]
Hi @kmcquade 
I did some research to find a solution to this requirement and I was able to get it to work but I think it is beyond the scope of this project since it has to do with loading the specs rather than comparing them.
Let's discuss it offline.
Could you please message me on slack: https://join.slack.com/t/oasdiff/shared_invite/zt-1wvo7wois-ttncNBmyjyRXqBzyg~P6oA

**Comment by reuvenharrison** [comment]
Hi @kmcquade 
Here's a solution to remove external references from the json spec before doing the diff, using the `jq` command.
The credit goes to @tcdsv.
```
jq 'walk(
  if type == "object" then
    with_entries(
      if .key == "$ref" and (.value | type == "string" and (test("^#") | not)) then
        {key: "type", value: "string"}
      else
        .
      end
    )
  else
    .
  end
)' openapi.json
```
