### ISSUE TITLE
Mysterious bug - "cannot unmarshal object into Go struct field TBis.paths of type []string"

### ISSUE THREAD

**Issue by kmcquade** [oasdiff/oasdiff#439]
# Describe the bug

I'm encountering a mysterious bug with one API Spec: https://github.com/kubero-dev/kubero/blob/main/swagger.json.

```
Error: failed to load base spec from "path/to/kubero.yml" with error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field TBis.paths of type []string
```

It doesn't give me more details than that. It seems to be a slightly buggy spec when I put it inside the [Swagger editor](https://editor.swagger.io/), but it should be able to load the spec.

# Steps to reproduce

1. Run these commands. I am using a blank openapi file for simplicity, and the base API Spec provided by the repository for the source code in question.

```bash
curl https://raw.githubusercontent.com/kubero-dev/kubero/main/swagger.json -o base.json
cat <<EOF >revision.yml
openapi: 3.0.0
paths: {}
EOF

oasdiff diff ./base.json ./revision.yml
```

2. Observe that the output contains a mysterious error.

![image](https://github.com/Tufin/oasdiff/assets/3422255/5e560e4b-46e6-45b0-905c-c7c6ed6d5c9c)

Text:
```
Error: failed to load base spec from "path/to/kubero.yml" with error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field TBis.paths of type []string
```

# Metadata

* oasdiff version: 1.9.5
* OS: Mac OS M2

**Comment by tcdsv** [comment]
The structural errors in the specification are responsible for this issue. This specification cannot be parsed because of these errors.

**Comment by reuvenharrison** [comment]
Specifically, this part of the path definitions is invalid:

            "bearerAuth": {
              "type": "http",
              "scheme": "bearer",
              "bearerFormat": "JWT"
            }

It would be nice to improve oasdiff's error in situations like this.
