### ISSUE TITLE
Header parameters and header fields on response objects should be case insensitive

### ISSUE THREAD

**Issue by CharString** [oasdiff/oasdiff#469]
**Describe the bug**
Header names should be considered case insensitive as mentioned in

https://spec.openapis.org/oas/latest.html#parameter-locations

> header - Custom headers that are expected as part of the request. Note that [[RFC7230](https://spec.openapis.org/oas/latest.html#bib-RFC7230)] states header names are case insensitive.

and https://spec.openapis.org/oas/latest.html#response-object

> headers 	Map[string, [Header Object](https://spec.openapis.org/oas/latest.html#headerObject) | [Reference Object](https://spec.openapis.org/oas/latest.html#referenceObject)] 	Maps a header name to its definition. [[RFC7230](https://spec.openapis.org/oas/latest.html#bib-RFC7230)] states header names are case insensitive. If a response header is defined with the name "Content-Type", it SHALL be ignored.

**To Reproduce**
```sh
$ cat param_base.yaml
```
```yaml 
openapi: 3.0.1
info:
  title: Test API
  version: v1
paths:
  /test:
    parameters:
      - in: header
        name: X-Case
        required: true
        schema:
          type: string
    get:
      tags:
        - Test
      responses:
        "200":
          description: Success
```
```sh
$ cat param_revision.yaml
```
```yaml
openapi: 3.0.1
info:
  title: Test API
  version: v1
paths:
  /test:
    parameters:
      - in: header
        name: x-case
        required: true
        schema:
          type: string
    get:
      tags:
        - Test
      responses:
        "200":
          description: Success
```
```sh
$ oasdiff breaking param_base.yaml param_revision.yaml --fail-on ERR
1 breaking changes: 1 error, 0 warning
error	[new-required-request-default-parameter-to-existing-path] at param_revision.yaml	
	in API GET /test
		added the new required 'header' request parameter 'x-case' to all path's operations
```

**Expected behavior**
No output and an exit code of 0.

**Desktop (please complete the following information):**
 - OS: Linux
 - rev: d7c8034df3e2a65cda1f68cc5b3fc242b075ba47

**Additional context**
https://spec.openapis.org/oas/latest.html#encoding-object Doens't mention case insensitivity, but I think that may be an oversight of the spec.

**Comment by reuvenharrison** [comment]
Hi @CharString.
I replicated the behavior. Thanks for reporting it.

The OpenAPI spec explicitly says that "Parameter names are case sensitive.", and as such, this is actually not a bug in oasdiff. [See this issue with a detailed discussion about the topic](https://github.com/OAI/OpenAPI-Specification/issues/457).

That being said, I can understand why you may want to ignore case during a diff, but before considering an enhancement to oasdiff, could you please explain how you end up with the case being different in the compared specs? Are either of the specs auto-generated? If so, it may be smarter to fix these tools.

Thanks,
Reuven

**Comment by CharString** [comment]
Hey @reuvenharrison,

And thanks for looking into it so promptly, and for the warm welcome on the Slack. 🙂

> The OpenAPI spec explicitly says that "Parameter names are case sensitive.", and as such, 

I don't know where that was paraphrased from. But [OpenAPI spec (also?) says](https://spec.openapis.org/oas/latest.html#format):

> All field names in the specification are case sensitive. This includes all fields that are used as keys in a map, except where explicitly noted that keys are case insensitive.

Now the crux is whether the aforementioned pointers to RFC7230, count as "explicitly noted that keys are case insensitive".

So let's reason about that from practicality: given using an OpenAPI spec means using HTTP, you can't count on the case of header names. Therefore two such specs which only differ in the case of header names, should be regarded equivalent.

For that exact reason in the Python ecosphere, two major http client libraries (httpx and requests) implement the http header map (dictionary) as having case-insensitive keys.

From my reading of the spec, I don't consider a case change in headers as breaking, *unless* there's also a change in the contents, such like a change to an enum.

> it may be smarter to fix these tools.

Yeah. Well, I don't know what the writer of the reference spec uses —it was even malformed, so they could probably use a linter. And therefore I don't consider "fixing my tools" to generate the same output as theirs, "smarter" 🙂. I prefer the old networking approach of being lenient in what I accept, strict in what I produce—, but for my implementation I use a library for part of it. So in the end, I'm interested in diffing the spec I generate from my implementation is *functionally* equivalent. `oasdiff` already gets me a lot of the way there by having flags for ignoring titles, summaries and descriptions.

**Comment by reuvenharrison** [comment]
I finally managed to get around to this.
Please try the new `--case-insensitive-headers` flag:
```
oasdiff breaking data/header-case/base.yaml data/header-case/revision.yaml --case-insensitive-headers
```

**Comment by CharString** [comment]
Thanks a lot. Works like a charm.

I thought it didn't, but it turned out `go build` didn't write to `bin/oasdiff` like the initial builds I made, but built a new `oasdiff` in the repo root. I should have run `make build` :sweat_smile:

**Comment by CharString** [comment]
PS Is this in the version that the GH action from oasdiff.com uses?

**Comment by reuvenharrison** [comment]
Yes, the Github action uses this docker image tufin/oasdiff:main which includes this PR.
But we will need to add the new flag `--case-insensitive-headers` to the action in order to use it.
Could you please open a relevant issue: https://github.com/oasdiff/oasdiff-action/issues/new
