### ISSUE TITLE
`response-property-became-required` is added for required properties that are newly added to response bodies

### ISSUE THREAD

**Issue by jguddas** [oasdiff/oasdiff#481]
**Describe the bug**
`response-property-became-required` and `response-required-property-added` both get added when a property gets added.

**To Reproduce**
1. Add `paths['some-endpoint'].get.respones.200.content['application/json']` to both a.json and b.json
2. Add a new property to `paths['some-endpoint'].get.respones.200.content['application/json'].properties` and `.required` to b.json 
1. Run `oasdiff changelog a.json b.json`

**Expected behavior**
Only `response-required-property-added` should be shown.

**Desktop (please complete the following information):**
 - OS: Mac
 - oasdiff version 1.10.5

**Comment by reuvenharrison** [comment]
Fixed by https://github.com/Tufin/oasdiff/pull/487
