### ISSUE TITLE
YAML/JSON field name typo: "reuired" -> "required"

### ISSUE THREAD

**Issue by raphaelhuefner** [oasdiff/oasdiff#492]
**Describe the bug**
When listing all checks in YAML or JSON format, a "reuired" field shows up, which is clearly a typo of the intended "required".

**To Reproduce**
1. Run `oasdiff checks --format yaml` or `oasdiff checks --format json`
2. Output: all entries have a "reuired" boolean field

**Expected behavior**
- All entries have a "required" boolean field.
- No entry has a "reuired" boolean field.

**Desktop (please complete the following information):**
 - OS: macOS
 - installed via `go install github.com/tufin/oasdiff@v1`

**Additional context**

I suggested this PR to fix the typo: https://github.com/Tufin/oasdiff/pull/491

**Comment by tcdsv** [comment]
thanks for the typo report and PR fix.
