### ISSUE TITLE
oasdiff error in composed mode when the same path appears in different files

### ISSUE THREAD

**Issue by anikitin** [oasdiff/oasdiff#500]
When I feed two OpenAPI files containing the same path but different methods to oasdiff changelog in composed mode, it fails 
with the following error:

```
Error: diff failed: duplicate endpoint (POST /test) found in get-test-openapi.yml and post-test-openapi.yml. You may add the x-since-date extension to specify order
```

It is expected that the combination of path+method should be unique (not just the path) across files.

Version 1.10.10. Command line:

```
oasdiff changelog "*-openapi.yml" "*-openapi.yml" -c -f text
```

See attachment. 
[oasdiff-duplicate-endpoint-bug.zip](https://github.com/Tufin/oasdiff/files/14489521/oasdiff-duplicate-endpoint-bug.zip)

**Comment by reuvenharrison** [comment]
Thanks. I replicated this. Working on a fix.
