### ISSUE TITLE
`latest` docker container (April 8th) introduces a bug that causes false positives

### ISSUE THREAD

**Issue by effervescentia** [oasdiff/oasdiff#519]
**Describe the bug**
The docker version of `oasdiff` finds errors between identical schema files

**To Reproduce**
1. We use docker, but the command essentially boils down to: `docker run tufin/oasdiff breaking --fail-on ERR`
2. Spec 1: [openapi.json](https://github.com/Tufin/oasdiff/files/14907256/openapi.json)
3. Spec 2: _the same as Spec 1_
4. Output:

```
1 breaking changes: 1 error, 0 warning
error	[request-property-one-of-removed] at /schemas/openapi.next.json	
	in API PUT /v1alpha1/generic
		removed 'BaseSchema[0], BaseSchema[1]' from the 'resources/items/kind' request property 'oneOf' list
```

**Expected behavior**
Since the files are identical, they should not be found to have a difference

**Desktop (please complete the following information):**
 - [latest Docker Image](https://hub.docker.com/layers/tufin/oasdiff/latest/images/sha256-39c755ed6f76644f891e6b5b60f5a857c027d6cf74da606d389deb8685d7b31e)

**Additional context**
~I notice there was no official tagged version released, it was only pushed to `latest`... perhaps this indicates something is off with your CI release process?~
I see that you have a `stable` tag on docker, I'll use that going forward since it appears to track the latest release from github (`v1.10.12`)

**Comment by reuvenharrison** [comment]
Thanks for reporting. I'll take a look at this ASAP. Please use the previous version until then.
