### ISSUE TITLE
Unmarshalling errors don't provide offset

### ISSUE THREAD

**Issue by ikonst** [oasdiff/oasdiff#524]
For example, given my OpenAPI spec I got the following error:
```
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into field Schema.type of type string
```

The error doesn't have a line + offset or even a byte offset, making it impossible to determine the culprit.

**Comment by reuvenharrison** [comment]
Could you please provide instructions to replicate this problem?

**Comment by ikonst** [comment]
For example, try diffing between
- `https://production.rutterapi.com/openapi/specs/2023-02-07.yaml`
- `https://production.rutterapi.com/openapi/specs/2023-03-14.yaml`

e.g.
```
oasdiff diff https://production.rutterapi.com/openapi/specs/2023-02-07.yaml https://production.rutterapi.com/openapi/specs/2023-03-14.yaml
```

**Comment by usualdesigner** [comment]
Same. @reuvenharrison is there any update?

**Comment by usualdesigner** [comment]
Ahh, seems like it relates https://github.com/Tufin/oasdiff/issues/52

**Comment by reuvenharrison** [comment]
I haven't forgotten about this, just need to close some other issues before getting to this.
Intuitively, without having replicated your examples yet, I would recommend verifying that your specs adhere to OAS 3.0 before running oasdiff.
Not sure which tools are available to do this but perhaps the community can recommend some.

**Comment by reuvenharrison** [comment]
Yes, it's OAS 3.1 which is not supported by oasdiff.

**Comment by nachmiasx** [comment]
Same error here:
Error: failed to load base spec from "openapi.json" with error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field TBis.components of type bool

is there any update about supporting to openapi 3.1.0 ?

**Comment by reuvenharrison** [comment]
Hi @nachmiasx,
Could you please provide the spec that you are trying to process with oasdiff?
Re. OpenAPI 3.1.0, no progress. Please see https://github.com/Tufin/oasdiff/issues/52 for details.
Reuven
