### ISSUE TITLE
Typo in description of incompatible changes

### ISSUE THREAD

**Issue by dalv666** [oasdiff/oasdiff#539]
https://github.com/Tufin/oasdiff/blob/b89acea39d422cddd1c6879850cbfc603d73aa0a/BREAKING-CHANGES-EXAMPLES.md?plain=1#L18
Typo. The test checks that the path variable has become an enum and not in the header. For the header, there is a separate test.

Similarly:
https://github.com/Tufin/oasdiff/blob/b89acea39d422cddd1c6879850cbfc603d73aa0a/checker/check_breaking_property_test.go?plain=1#L185

Solution:
`[changing an existing path param to enum is breaking](https://github.com/Tufin/oasdiff/blob/b89acea39d422cddd1c6879850cbfc603d73aa0a/checker/check_breaking_property_test.go?plain=1#L185)`

**Comment by reuvenharrison** [comment]
Hi @dalv666 ,
Could you please share the use case: how are you using the test descriptions?
Thanks,
Reuven

**Comment by dalv666** [comment]
The description of backwards incompatible is not clearly described, so you have to determine what this means from the source code. The description helps you find the test using text search. Otherwise it would be more reliable to search for the code by identifier. Yes, this can be done by link in description, but it does not work in IDE.
