### ISSUE TITLE
Checksums do not match while using install script.

### ISSUE THREAD

**Issue by Remki** [oasdiff/oasdiff#565]
**Describe the bug**
install.sh returns `Checksums do not match` while building docker image on Linux_x86_64 machine.

**To Reproduce**
1. run curl -fsSL https://raw.githubusercontent.com/tufin/oasdiff/main/install.sh | sh on Linux_x86_64

**Expected behavior**
It should install without error

**Desktop (please complete the following information):**
 - Linux_x86_64

**Additional context**

I have following Dockerfile
`FROM ubuntu:16.04

RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://raw.githubusercontent.com/tufin/oasdiff/main/install.sh | sh
`
I'm building it using `docker build -t package_name .`, it works properly on MacOs, but while building it on Linux_x86_64 arch it returns following log

`
 > [3/3] RUN curl -fsSL https://raw.githubusercontent.com/tufin/oasdiff/main/install.sh | sh:
#6 1.472 sh: 130: [: linux: unexpected operator
#6 1.477 Temporary directory is /tmp/tmp.IG25IOBuQ3
#6 1.477 Downloading https://github.com/Tufin/oasdiff/releases/download/v1.10.17/oasdiff_1.10.17_linux_x86_64.tar.gz
#6 2.043 Validating checksum
#6 2.044 https://github.com/Tufin/oasdiff/releases/download/v1.10.17/checksums.txt
#6 3.298 Checksums do not match
` 

From what I see, this architecture should be supported, however it is not listed in [checksums.txt](https://github.com/Tufin/oasdiff/releases/download/v1.10.17/checksums.txt)
`
d28dbecd45fd657a0c5814626686155addb9490ab8db07160ccbff2745289222  oasdiff_1.10.17_darwin_all.tar.gz
0fcaa93d61e74c8e4b417a545cbb478d68c50a6bbe732d56f92ee14a1c6577d8  oasdiff_1.10.17_linux_amd64.apk
1ba966cc5e36c141328e235087dca407b7e0a24c4e99b9619f50deedd6193a19  oasdiff_1.10.17_linux_amd64.deb
011dd531c0b0435899b33774d5d96e6a3baa5a7177db3bef408e6929c6abdf17  oasdiff_1.10.17_linux_amd64.rpm
718a3629f66f1c04f6e4e6a61aa0b042621a6b35e8d80fdc87c5d40e3f0e949e  oasdiff_1.10.17_linux_amd64.tar.gz
da0944918aa4b1728cf15927451f5ae1f407aff1888208e6878324f6375f9139  oasdiff_1.10.17_linux_arm64.apk
a1eb5034d1f324bfd750f9aa7113c458b66253e5914bb18100e59cfc945c2399  oasdiff_1.10.17_linux_arm64.deb
d55822e91cee356bc7d35e485fb34d7165e8905514c3f189793d49dff2ee69c2  oasdiff_1.10.17_linux_arm64.rpm
63d115f541be901337fe3217e2a07ed3dfde5b0ce33aaf152ed9880256b5513e  oasdiff_1.10.17_linux_arm64.tar.gz
9e234003d4fc113a3981cda557eb4745dcaaa663e45194eb6081c9135b77aa7b  oasdiff_1.10.17_windows_amd64.tar.gz
4923df8ed0d367bde22d466eb0cb9a0c6f8a378b88e913fbb8d3541d8c27097d  oasdiff_1.10.17_windows_arm64.tar.gz
`

Alternatively, is there any way to use your docker image with disabled TLS, or to configure TLS for self-signed certificate?

**Comment by omairvaiyani** [comment]
Noticed this in our Github Actions ubuntu-latest x64 runner

> Edit

If anyone else runs into this whilst waiting for a fix, you can use `setup-binary-action` Github Action to manually install the binary

```yaml
- name: Manually install oasdiff
  uses: plinioh/setup-binary-action@v1.0.0
  with:
     binaryName: oasdiff
     binaryUrl: https://github.com/Tufin/oasdiff/releases/download/v1.10.17/oasdiff_1.10.17_linux_amd64.tar.gz
     binaryPathInArchive: oasdiff
```

**Comment by reuvenharrison** [comment]
@johnowl

**Comment by scastria** [comment]
I ran into this too with version 1.10.18.  It works on my mac using arm64 platform, but not linux/amd64.  I am installing this in my own docker image with a RUN command which fails because of this.

**Comment by scastria** [comment]
I see the problem.  It isn't a checksum problem at all.  the install script tries to install the x86_64 binary which doesn't exist.  It needs to install the amd64 binary instead

**Comment by scastria** [comment]
I changed the following line to fix the issue:
![image](https://github.com/Tufin/oasdiff/assets/4534494/1af6de41-265a-49fd-8a70-99c1822621f4)

**Comment by scastria** [comment]
@reuvenharrison I see a new release was made 2 hours ago.  I was hoping it was fixing this issue.  It is a one liner change as shown in my screenshot above.

**Comment by reuvenharrison** [comment]
Hi @scastria 
Could you please submit a pull request with this fix?
Thanks,
Reuven

**Comment by mahirpiy** [comment]
@reuvenharrison @scastria  I opened a pull request with the above fix
