### ISSUE TITLE
Removing an enum member is not caught as a breaking change

### ISSUE THREAD

**Issue by mheguy** [oasdiff/oasdiff#595]
**Describe the bug**
Removing an enum member is not caught as a breaking change

**To Reproduce**
1. `oasdiff breaking before.yaml after.yaml`
2. before:
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
paths:
  /pets:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                enum:
                  - GOOD_DOG
                  - BAD_DOG
                  - CAT
```
3. after:
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
paths:
  /pets:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                enum:
                  - GOOD_DOG
                  - BAD_DOG
```
4. Output (changelog also run to show the tool working):
![image](https://github.com/user-attachments/assets/0aa248bd-4a8b-4ea5-9cc4-04db6dc473c4)

**Expected behavior**
The removal of an enum member should be listed as a breaking change.

**Desktop (please complete the following information):**
Tested running locally on Windows and Linux, also tested docker container.

**Additional context**
The issue is not present in the web app (https://www.oasdiff.com/diff-calculator):
![image](https://github.com/user-attachments/assets/df8d4ade-642d-47f0-b36f-f452a5ead764)

**Comment by reuvenharrison** [comment]
Hi @mheguy,
If the enum value would have been removed from a **request** it would have been a breaking-change.
In your example above, the enum value was removed from the **response**.
Oasdiff reports this change as **informational** as can be seen with the changelog command:
<img width="757" alt="Screenshot 2024-08-27 at 10 06 04" src="https://github.com/user-attachments/assets/289211e6-7798-461a-b954-fb039425ebc5">

By the way, you can use the `oasdiff checks` command to research the relevant checks.
`oasdiff checks -t remove | grep enum`

I hope that helps.

**Comment by mheguy** [comment]
You're very right, removing an enum value is not a breaking change. Good catch.

In that case, where should I file a bug for the web version? Because one way or another: the tools don't agree with one another.

**Comment by reuvenharrison** [comment]
Fixed.
Thanks for reporting this.
