### ISSUE TITLE
 map key not found

### ISSUE THREAD

**Issue by akhilarao29** [oasdiff/oasdiff#602]
Hello,
I am experimenting with oasdiff and also an open api spec of SysML. Here is the link where you can find the spec: http://sysml2.intercax.com:9000/docs/, I have downloaded the same and named it as openspec1.json. Made a copy of it, made some changes and renamed it as openspec2.json.
When i try to find the difference using the command: docker run --rm -t -v $(pwd):/specs:ro -w /specs tufin/oasdiff:latest diff openspec1.json  openspec2.json i get the following error "failed to load base spec from "openspec1.json": map key "Error" not found"
I have tried with the previous versions as well and received the same error.
Attaching openspec1.json and openspec2.json
[openspec1.json](https://github.com/user-attachments/files/16885334/openspec1.json)
[openspec2.json](https://github.com/user-attachments/files/16885338/openspec2.json)

**Comment by akhilarao29** [comment]
Also attaching the openspec1.json and openspec2.json
[Uploading openspec1.json…]()

**Comment by akhilarao29** [comment]
[openspec2.json](https://github.com/user-attachments/files/16885309/openspec2.json)

**Comment by reuvenharrison** [comment]
The spec is invalid. It contains references to #/components/schemas/Error which doesn't exist.

Also, it is using OpenAPI v3.1.0 which isn't supported by oasdiff.

This one looks better:
https://github.com/Systems-Modeling/SysML-v2-API-Java-Client/blob/master/api/openapi.yaml

**Comment by akhilarao29** [comment]
Hello,
Are there any plans to support 3.1?

**Comment by reuvenharrison** [comment]
Realistically, no.
Please see this discussion about 3.1 support: https://github.com/Tufin/oasdiff/issues/52
