### ISSUE TITLE
Reference issue in a valid yaml file

### ISSUE THREAD

**Issue by jval-sellsy** [oasdiff/oasdiff#605]
When using oasdiff on our open api schema, we have a reference issue.

```
Error: failed to load base spec from "oas/sellsy-v2-prod.yaml": bad data in "#/components/schemas/Verify" (expecting ref to response object)
```

The schema is available here : https://api.sellsy.com/doc/v2/dist/sellsy.v2.latest.yaml
And has been validated

Any idea on the issue here ?

**Comment by reuvenharrison** [comment]
The reference is placed immediately under response 204 and should therefor point to a response object but instead it points to a schema object.

Perhaps the intention was to place this ref under content/schema as in the preceding response 201.

**Comment by jval-sellsy** [comment]
Thanks for your answer.
I confirm that moving from : 

```
        '204':
          '$ref': '#/components/schemas/Verify'

```
To

```
        '204':
          'content':
            'application/json':
              'schema':
                '$ref': '#/components/schemas/Verify'
```

fix the issue.
I'll see with the dev team if they can change the format.

Thank you :smiley:
