### ISSUE TITLE
Support OAS 3.1.0

### ISSUE THREAD

**Issue by alex-statsig** [oasdiff/oasdiff#606]
I'd like to use this library to detect breaking changes in a OAS v3.1.0 schema. Currently, it fails to parse the schema due to the breaking change of "exclusiveMinimum" being a number instead of a boolean in v3.1.0.

I'm not sure if "exclusiveMinimum" is the only thing unsupported for v3.1.0 (ex. `type` can be an array instead of a single value, but that seems to pass parsing already), but in my particular case its the only thing blocking parsing.

Curious generally if there's plans to support v3.1.0, or if we can start with a small patch around this particular breaking change (since it seems fairly easy to support both versions of this particular field at least)

**Comment by reuvenharrison** [comment]
Please see https://github.com/Tufin/oasdiff/issues/52
