### ISSUE TITLE
No breaking changes reported for path parameters

### ISSUE THREAD

**Issue by amit-ng** [oasdiff/oasdiff#608]
**Describe the bug**
Breaking changes are not reported for path parameter changes on the latest released version.

**To Reproduce**
1. The command-line, for example: `oasdiff breaking base.yaml revision.yaml --fail-on ERR`
2. [base.txt](https://github.com/user-attachments/files/17031504/base.txt)
3. [revision.txt](https://github.com/user-attachments/files/17031506/revision.txt)
4. Output

**Expected behavior**
A breaking change should be reported. 
[base.txt](https://github.com/user-attachments/files/17031504/base.txt)
[revision.txt](https://github.com/user-attachments/files/17031506/revision.txt)

**Desktop (please complete the following information):**
 - MacOS

**Additional context**
`oasdiff diff` shows diff correctly but it's not getting reported on `oasdiff breaking`

**Comment by reuvenharrison** [comment]
Please check if this solves this problem: https://github.com/Tufin/oasdiff/blob/main/docs/COMMON-PARAMS.md

**Comment by amit-ng** [comment]
Awesome, this works. Thanks for sharing!
