### ISSUE TITLE
Report a removal of deprecated endpoint in oasdiff changelog

### ISSUE THREAD

**Issue by realitycheck** [oasdiff/oasdiff#619]
**Is your feature request related to a problem? Please describe.**

Seems like there is no indication in changelog output in case of removal of deprecated endpoint.

**Describe the solution you'd like**
Info in changelog about removed endpoint.

**Describe alternatives you've considered**
None.

**Additional context**

oasdiff version: 1.10.26

There trails of endpoint-removed messages are existed in code but no implementation or usage seems found: https://github.com/Tufin/oasdiff/blob/main/checker/generator/messages.yaml#L8

**Comment by reuvenharrison** [comment]
This is by design. Removing a deprecated resource is not considered breaking.
Please read this for more details and let me know if you have any further comments:
https://github.com/Tufin/oasdiff/blob/main/docs/DEPRECATION.md

**Comment by reuvenharrison** [comment]
Actually, you have a point.
I am going to add an info-level check when removing an endpoint after deprecation.
