### ISSUE TITLE
oasdiff.exe seems to infinite loop

### ISSUE THREAD

**Issue by BlitzkriegSoftware** [oasdiff/oasdiff#68]
`oasdiff.exe -base 202201200951-confluxeyservicesint.json -revision 202201280912-confluxeyservicesint.json --breaking-only -format yaml`

Both JSON files are OpenAPI3 and the JSON is valid (via JSONLINT). 

O/S: Windows 10 Patched

`go version`
`go version go1.17.6 windows/amd64`

**To Reproduce**
1. Use the sample files
2. Repeat command above
3. Observed infinite loop

**Expected behavior**
Diff is generated in YAML

**Notes**
1. Only seems to impact some file comparisons, others work fine
2. I can supply the problematic files for repo, please e-mail `stuart.williams1@ey.com` and I'll send them to you
3. I apologize for lacking more detailed debugging, I don't speak GO, yet

**Comment by reuvenharrison** [comment]
Thanks for reporting the issue.
I emailed you to request the files.
