### ISSUE TITLE
OperationID considered breaking changes?

### ISSUE THREAD

**Issue by finnfabians** [oasdiff/oasdiff#97]
**Describe the bug**
Changes in operation ids are considered breaking API changes

**To Reproduce**
1. Generate 2 specs with the same API but differing operation ids

**Expected behavior**
No breaking changes should be found

**Comment by reuvenharrison** [comment]
Fixed by https://github.com/Tufin/oasdiff/pull/98

Note that changes to "OperationID" will be considered non-breaking both under Methods *and* under Links.
Please confirm whether this makes sense to you.

**Comment by finnfabians** [comment]
Well, that was quick! Yes that makes sense to me.
